jaffle_shop:

  target: dev
  outputs:
    dev:
      type: snowflake
      account: OXOCODR-NWB79451
      user: JIANXIANGLUO
      password: 
      role: ACCOUNTADMIN
      database: UTIL_DB
      schema: PUBLIC
      threads: 4

      warehouses: COMPUTE_WH
